version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "/wait-for-it.sh", "rabbitmq3:5672", "--"]
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=testpasswd123
      - DEBUG=1
      - RABBITMQ_HOST=rabbitmq3
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - redis
      - db
      - rabbitmq3

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=testpasswd123
  

  redis:
    image: redis:7.2.5-alpine

  celery:
    restart: always
    build:
      context: .
      args:
        - DEV=true
    command: ["sh", "-c", "celery -A app worker --loglevel=error"]
    volumes:
      -  ./app:/app
    depends_on:
      - app
      - rabbitmq3
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  rabbitmq3:
    image: rabbitmq:3.13.3-alpine
    container_name: "rabbitmq3"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  flower:
   restart: always
   image: mher/flower
   command: ["celery", "flower", "-A", "app", "--broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}//"]
   ports:
    - "5555:5555"
   depends_on:
    - rabbitmq3
    - celery
   environment:
    - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}//

volumes:
  dev-db-data:
  dev-static-data:
